server:
  port: 8999
web:
  security:
    log-page: "/login.html"
    logout: "/logout"
    login-url: "/login"
    no-authority-urls: ["/home.html" ]
    authority-urls: [ ]
    is-ignore-other-url: false
    target-url: "/index.html"
    target-url-parameter: ""

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "lzl0502"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        # 最大连接数
        max-active: 10
        # 最大阻塞时间
        max-wait: 12000
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 1
        # 超时时间
        timeout: 12000
  security:
    oauth2:
      resource:
        jwt:
          key-uri: "http://127.0.0.1:8999/oauth/token_key"
      client:
        client-id: test
        client-secret: 123456
        user-authorization-uri: "http://127.0.0.1:8999/oauth/authorize"
        access-token-uri: "http://127.0.0.1:8999/oauth/token"
        grant-type: authorization_code,password,refresh_token
        scope: all
logging:
  level:
    root: info


redisson:
  url: "redis://127.0.0.1:6379"
